[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/build"

[build.environment]
  NODE_ENV = "production"
  CI = "true"
  DISABLE_ESLINT_PLUGIN = "true"
  REACT_APP_BACKEND_URL = "https://trading-simulator-iw7q.onrender.com"
  REACT_APP_BACKEND_WS_URL = "wss://trading-simulator-iw7q.onrender.com"
  REACT_APP_API_BASE_URL = "https://trading-simulator-iw7q.onrender.com"
  REACT_APP_ENV = "production"